### ISSUE TITLE
Parameters & return value of getters/setters in object literals are not correctly extracted

### ISSUE THREAD

**Issue by tomchen** [TypeStrong/typedoc#1475]
## Search terms

getter setter function accessor object literal {} parameter return value incorrect wrong bug issue class

## Expected Behavior

```ts
export class Cls {
  a = 2
  method(str: string): string {
    return str
  }
  get getIt(): number {
    return this.a
  }
  set setIt(n: number) {
    this.a = n
  }
}
```

![2021-01-21_114315](https://user-images.githubusercontent.com/529949/105340558-56ad5700-5bde-11eb-9f16-9a3b527055ce.png)

Getters and setters in class are fine, their parameters and return value are correctly extracted.

It is expected getters and setters in `{}` object are treated the same way.

## Actual Behavior

```ts
let a = 2

export const obj = {
  method: (str: string): string => str,
  get getIt(): number {
    return a
  },
  set setIt(n: number) {
    a = n
  },
}
```

![2021-01-21_114348](https://user-images.githubusercontent.com/529949/105340800-a9870e80-5bde-11eb-8535-b2a1ce9d8dab.png)

No, typedoc can't extract parameters and return value of the getters and setters in `{}` object.

I explicitly named the getter and the setter `getIt` and `setIt` respectively for demonstration purposes, normally we use the same name for the getter and setter that gets and sets the same thing. If I use `get it()` and `set it()`, il would be worse: the setter `it()`'s data would overwrite the getter `it()`'s and output just one `it()` function. Again no problem with getter and setter with the same name in a class.

## My configurations

I don't think devDependencies play any role in this bug but here's my devDependencies in package.json:

```json
  "devDependencies": {
    "@types/jest": "^26.0.19",
    "@typescript-eslint/eslint-plugin": "^4.11.1",
    "@typescript-eslint/parser": "^4.11.1",
    "eslint": "^7.16.0",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-prettier": "^3.3.0",
    "jest": "^26.6.3",
    "prettier": "^2.2.1",
    "ts-jest": "^26.4.4",
    "ts-loader": "^8.0.13",
    "typedoc": "^0.20.16",
    "typescript": "^4.1.3"
  }
```

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5"
  }
}
```

(or change the target to any versions >= es5)

## Environment

-   Typedoc version: 0.20.16
-   TypeScript version: 4.1.3
-   Node.js version: v12.18.1
-   OS: Windows 10

**Comment by Gerrit0** [comment]
Very weird... thanks for the report! Looks like this is an issue with the themes, the JSON output includes what I would expect.

**Comment by tomchen** [comment]
I don't know, but I initially found this issue when I was using [typedoc-plugin-markdown](https://github.com/tgreyuk/typedoc-plugin-markdown), I assume typedoc-plugin-markdown does not go through the theme, but uses the JSON output?

**Comment by Gerrit0** [comment]
typedoc-plugin-markdown uses the theme architecture - mostly. It replaces some parts of it with generation specific to markdown.

Fixing this on the theme side likely won't immediately fix in on the plugin side, but it's broken there too￼

**Comment by Gerrit0** [comment]
Well that was really annoying to fix... I really hate handlebars. This likely won't fix the issue with typedoc-plugin-markdown, but it works properly now for the default theme at least.

https://github.com/TypeStrong/typedoc-default-themes/commit/947e85a3e4afda73db341de48ba0ebc21964cd9a

**Comment by Gerrit0** [comment]
Fix released in 0.20.17

**Comment by tomchen** [comment]
Thx

But it still can't deal with getter and setter with a same name:

```ts
let a = 2

export const obj = {
  method: (str: string): string => str,
  get it(): number {
    return a
  },
  set it(n: number) {
    a = n
  },
}
```
The getter `it()` and the setter `it()` are "merged" into one.

**Comment by Gerrit0** [comment]
Doing that for types makes some sense - but yeah... not sure what I was thinking combining them for the "parameters" helper.
