### ISSUE TITLE
No reflection on object literals

### ISSUE THREAD

**Issue by williamkbentley** [TypeStrong/typedoc#901]
From TypeDoc src\lib\utils\component.ts:
`const childMappings: {host: ChildableComponent<any, any>, child: Function}[] = [];`

Generates:
![image](https://user-images.githubusercontent.com/38542573/48509384-f4e34c80-e81e-11e8-9d59-0245a93c475d.png)

No information on the object literal, just _object_.

Likewise on this example:
`/** Email details */  `
`public email?: { id: string, isVerified?: boolean }`

Generates:
![image](https://user-images.githubusercontent.com/38542573/48510069-d2eac980-e820-11e8-8109-fe086a1635e1.png)

Again, just _object_. Is it possible to get reflection information on the object literal?

**Comment by 9oelM** [comment]
It's partly working. See below:

![default](https://user-images.githubusercontent.com/22465806/50904587-03876200-1464-11e9-885e-7e3f02d98e6a.PNG)

And my test code to produce docs is this:
```ts
class Test {
    public email?: { id: string, isVerified?: boolean }
}

const childMappings: {host: number, child: Function}[] = [];

const test2 = {
    hi: "hi",
    test: "test"
}
```

We can see that `email` property is shown with its own object properties. Am I reproducing something wrong, or is typedoc updated to make some changes on this matter? 

On the other hand, `childMappings` would be rendered the same as what @williamkbentley suggested:
![image](https://user-images.githubusercontent.com/22465806/50904789-94f6d400-1464-11e9-81ab-f74793f2adaf.png)

So I really don't know what's happening here. I need some more verification...!? @williamkbentley

**Comment by williamkbentley** [comment]
I think narrowed part of the issue down to `--excludeNotExported`. When that option is on the object literal properties are not included:
![image](https://user-images.githubusercontent.com/38542573/50918310-df993180-140d-11e9-9f85-8c8980aaaccf.png)

Same class without `--excludeNotExported`:
![image](https://user-images.githubusercontent.com/38542573/50918379-15d6b100-140e-11e9-8bef-eecff1aba680.png)

Using v0.14.0

**Comment by 9oelM** [comment]
Weird :worried: 
I will have a look at this if I have some time.

**Comment by th0r** [comment]
Are there any news guys? I face the same problem and here is a minimal reproduction:

#### Test code
```ts
export interface MyEvent<Type extends string, Payload> {
  type: Type;
  payload?: Payload;
}

export type FooEvent = MyEvent<'foo', {
  some: string;
  data: number;
}>
```
#### typedoc.json
```json
{
  "src": [
    "./test.ts"
  ],
  "mode": "file",
  "module": "umd",
  "target": "es5",
  "out": "docs"   
}
```
#### Generated docs
![image](https://user-images.githubusercontent.com/302213/68496212-d877c580-0262-11ea-949b-bd3031855329.png)

It would be great to see a list of properties for payload e.g.
```
Payload
some: string
data: number
```

**Comment by Gerrit0** [comment]
This has been fixed in 0.16

![image](https://user-images.githubusercontent.com/19329837/72479678-6798e080-37b2-11ea-8bf0-293f6fcb1115.png)

**Comment by liamross** [comment]
I'm still having this issue with `@next` (`typedoc@^0.17.0-3`) with the new `--mode library` option:

```ts
export type TOptions = string | {number?: number; [target: string]: any};
```

Generated:

```ts
TOptions
Ƭ TOptions: string | object
```

Config:

```sh
"typedoc": "typedoc --out packages/site/docs/api packages/core/src/index.ts --mode library --readme none --excludePrivate --plugin typedoc-plugin-markdown --theme docusaurus2",
```

**Comment by Gerrit0** [comment]
Huh, that's weird, I would have expected it to render `string | { number?: number }` (the themes don't handle index signatures correctly yet, need to open a bug for that)

**Comment by Gerrit0** [comment]
I can't reproduce with the default theme - this seems to be a bug with typedoc-plugin-markdown.

**Comment by liamross** [comment]
Thanks, I'll report an issue there instead
